#!/bin/bash
# =============================================================================
# 09b-seed-schedule.sh — Configurazione seed periodico del palinsesto CineBase
# Server: malafronte-oci-s1 (ARM Ubuntu 24.04)
#
# Cosa fa:
#   - Genera lo script ~/docker/cinebase/seed-schedule.sh
#   - Configura il cron job per esecuzione ogni 1° e 15 del mese alle 4:00
#
# Lo script generato invoca il seeder con:
#   --append-schedule --weeks 2
#
# Il seeder è idempotente (UPSERT) e aggiunge 2 settimane di programmazione
# a partire dall'ultimo show presente nel database.
#
# Prerequisito:
#   1. Stack CineBase già deployato (09-setup-cinebase.sh già eseguito)
#   2. Primo seed manuale già eseguito con data corrente:
#        cd ~/docker/cinebase
#        docker compose run --rm seeder --append-schedule --start-date $(date +%Y-%m-%d) --weeks 2
#
# Da eseguire come:  bash 09b-seed-schedule.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  source <(sed 's/\r$//' "$SCRIPT_DIR/.env")
else
  echo "ERRORE: File .env non trovato in $SCRIPT_DIR"
  echo "Copia .env.example in .env e inserisci i valori reali."
  exit 1
fi

echo "=== [09b] Setup seed periodico palinsesto CineBase ==="

DOCKER_DIR="$HOME/docker"
CINEBASE_DIR="$DOCKER_DIR/cinebase"

# ── 1. Verifica che lo stack CineBase esista ──────────────────────────────
if [ ! -f "$CINEBASE_DIR/docker-compose.yml" ]; then
  echo "ERRORE: Stack CineBase non trovato in $CINEBASE_DIR"
  echo "Esegui prima 09-setup-cinebase.sh"
  exit 1
fi

# ── 2. Script di seed periodico (embedded) ────────────────────────────────
echo ">> Creazione script $CINEBASE_DIR/seed-schedule.sh..."
cat > "$CINEBASE_DIR/seed-schedule.sh" << 'SEEDEOF'
#!/bin/bash
# =============================================================================
# seed-schedule.sh — Aggiunge 2 settimane di programmazione al palinsesto
# Generated by 09b-seed-schedule.sh
#
# Invoca il seeder con --append-schedule --weeks 2.
# Il seeder è idempotente (UPSERT) e auto-rileva la data di partenza
# dall'ultimo show presente nel database.
# =============================================================================
set -euo pipefail

LOG_FILE="$HOME/docker/cinebase/seed-schedule.log"
log() { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*" | tee -a "$LOG_FILE"; }

log "=== Inizio seed programmazione ==="
cd "$HOME/docker/cinebase"

if docker compose run --rm seeder --append-schedule --weeks 2 >> "$LOG_FILE" 2>&1; then
    log "Seed completato con successo"
else
    log "ERRORE: seed fallito"
fi
SEEDEOF

chmod +x "$CINEBASE_DIR/seed-schedule.sh"
echo "   $CINEBASE_DIR/seed-schedule.sh creato."

# ── 3. Cron job per seed ogni 1° e 15 del mese alle 4:00 ────────────────
echo ">> Configurazione cron job (seed palinsesto ogni 1° e 15 del mese alle 4:00)..."
CRON_LINE="0 4 1,15 * * $CINEBASE_DIR/seed-schedule.sh"
(crontab -l 2>/dev/null | grep -v '^CRON_TZ=' | grep -v 'seed-schedule.sh' || true; echo "CRON_TZ=Europe/Rome"; echo "$CRON_LINE") | crontab -
echo "   Cron job configurato."

echo ""
echo "=== Seed periodico configurato ==="
echo ""
echo "Script creato sul server:"
echo "  $CINEBASE_DIR/seed-schedule.sh   — aggiunge 2 settimane di programmazione"
echo ""
echo "Test manuale:"
echo "  $CINEBASE_DIR/seed-schedule.sh"
echo ""
echo "Verifica cron:"
echo "  crontab -l | grep seed"
echo ""
echo "Log:"
echo "  $CINEBASE_DIR/seed-schedule.log"
