#!/bin/bash
# =============================================================================
# 09c-status-report.sh — Report giornaliero via Telegram
# Server: malafronte-oci-s1 (ARM Ubuntu 24.04)
#
# Cosa fa:
#   - Genera lo script ~/docker/status-report.sh
#   - Configura il cron job per ogni giorno alle 15:00 UTC (17:00 CEST)
#
# Il report giornaliero include:
#   - Stato di tutti i container Docker (operativi/fermi)
#   - Occupazione bucket OCI Object Storage (s1-backup)
#   - Stato dei database (PostgreSQL, MariaDB)
#
# Prerequisito:
#   1. TELEGRAM_BOT_TOKEN e TELEGRAM_CHAT_ID valorizzati in .env
#   2. OCI CLI installata e Instance Principal configurato
#
# Da eseguire come:  bash 09c-status-report.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  source <(sed 's/\r$//' "$SCRIPT_DIR/.env")
else
  echo "ERRORE: File .env non trovato in $SCRIPT_DIR"
  echo "Copia .env.example in .env e inserisci i valori reali."
  exit 1
fi

echo "=== [09c] Setup report giornaliero Telegram ==="

DOCKER_DIR="$HOME/docker"

# ── 1. Verifica credenziali Telegram ──────────────────────────────────────
if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
  echo "ERRORE: TELEGRAM_BOT_TOKEN e/o TELEGRAM_CHAT_ID non configurati in .env"
  echo "Configurali nel .env e riprova (vedi docs/guida-telegram-bot.md)"
  exit 1
fi

# ── 2. Script di report (embedded) ────────────────────────────────────────
echo ">> Creazione script $DOCKER_DIR/status-report.sh..."
cat > "$DOCKER_DIR/status-report.sh" << 'REPORTEOF'
#!/bin/bash
# =============================================================================
# status-report.sh — Report giornaliero dello stato del server via Telegram
# Generated by 09c-status-report.sh
# =============================================================================
set -euo pipefail

# Assicura che oci CLI sia trovabile dal cron (PATH minimale di default)
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TMP_MSG="/tmp/telegram_report.json"

# ── Carica credenziali Telegram ───────────────────────────────────────────
if [ -f "$SCRIPT_DIR/.env" ]; then
  source <(sed 's/\r$//' "$SCRIPT_DIR/.env")
elif [ -f "$SCRIPT_DIR/../.env" ]; then
  source <(sed 's/\r$//' "$SCRIPT_DIR/../.env")
elif [ -f "$HOME/scripts/.env" ]; then
  source <(sed 's/\r$//' "$HOME/scripts/.env")
fi

if [ -z "${TELEGRAM_BOT_TOKEN:-}" ] || [ -z "${TELEGRAM_CHAT_ID:-}" ]; then
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERRORE: credenziali Telegram non configurate" >&2
  exit 1
fi

# ── Utility ───────────────────────────────────────────────────────────────
send_tg() {
  local text="$1"
  jq -n --arg chat_id "$TELEGRAM_CHAT_ID" --arg text "$text" \
    '{chat_id: $chat_id, text: $text, parse_mode: "HTML"}' > "$TMP_MSG"
  curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
    -H "Content-Type: application/json" \
    -d "@$TMP_MSG" > /dev/null
  rm -f "$TMP_MSG"
}

container_up() {
  docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "$1"
}

icon() { container_up "$1" && echo "✅" || echo "❌"; }

# ── Data in italiano ──────────────────────────────────────────────────────
DOW=$(TZ="Europe/Rome" date '+%u')
DAY=$(TZ="Europe/Rome" date '+%-d')
MONTH=$(TZ="Europe/Rome" date '+%-m')
YEAR=$(TZ="Europe/Rome" date '+%Y')
case "$DOW" in
  1) GIORNO="Lunedì" ;; 2) GIORNO="Martedì" ;; 3) GIORNO="Mercoledì" ;;
  4) GIORNO="Giovedì" ;; 5) GIORNO="Venerdì" ;; 6) GIORNO="Sabato" ;;
  7) GIORNO="Domenica" ;;
esac
case "$MONTH" in
  1) MESE="Gennaio" ;;  2) MESE="Febbraio" ;; 3) MESE="Marzo" ;;
  4) MESE="Aprile" ;;   5) MESE="Maggio" ;;   6) MESE="Giugno" ;;
  7) MESE="Luglio" ;;   8) MESE="Agosto" ;;   9) MESE="Settembre" ;;
  10) MESE="Ottobre" ;; 11) MESE="Novembre" ;; 12) MESE="Dicembre" ;;
esac
DATA_ITA="${GIORNO} ${DAY} ${MESE} ${YEAR}"

# ── 1. Stato container ────────────────────────────────────────────────────
echo ">> Raccolta stato container..."

total=0; ok=0
group_icon() {
  local names="$1"
  local all_up=true
  for n in $names; do
    total=$((total + 1))
    if container_up "$n"; then
      ok=$((ok + 1))
    else
      all_up=false
    fi
  done
  $all_up && echo "✅" || echo "❌"
}

srvs=""
srvs+="$(printf '   %-10s %s %s\n' "proxy"     "traefik"                    "$(icon traefik)")"$'\n'
srvs+="$(printf '   %-10s %s %s\n' "monitor"   "netdata $(icon netdata), portainer $(icon portainer)" "")"$'\n'
srvs+="$(printf '   %-10s %s %s\n' "registry"  "registry"                   "$(icon registry)")"$'\n'
srvs+="$(printf '   %-10s %s %s\n' "git"       "forgejo $(icon forgejo) | db $(icon forgejo-db) | runner1 $(icon forgejo-runner1) runner2 $(icon forgejo-runner2)" "")"$'\n'
srvs+="$(printf '   %-10s %s %s\n' "cinebase"  "mariadb $(icon cinebase-mariadb), api $(icon cinebase-filmapi), web $(icon cinebase-web)" "")"$'\n'
srvs+="$(printf '   %-10s %s %s\n' "analytics" "postgres $(icon analytics-postgres), waline $(icon analytics-waline), umami $(icon analytics-umami)" "")"$'\n'
srvs+="$(printf '   %-10s %s %s\n' "web"       "landing"                    "$(icon landing)")"

for n in traefik portainer registry forgejo forgejo-db forgejo-runner1 forgejo-runner2 \
         netdata cinebase-mariadb cinebase-filmapi cinebase-web \
         analytics-postgres analytics-waline analytics-umami landing; do
  total=$((total + 1))
  container_up "$n" && ok=$((ok + 1)) || true
done

if [ "$ok" -eq "$total" ]; then
  status_emoji="🟢"
  status_line="Tutti operativi (${ok}/${total})"
else
  status_emoji="🟡"
  status_line="${ok}/${total} operativi"
fi

# ── 2. Backup OCI ─────────────────────────────────────────────────────────
echo ">> Raccolta statistiche backup..."
BUCKET="${BACKUP_BUCKET_NAME:-s1-backup}"
backup_line="non disponibile"

if command -v oci &> /dev/null; then
  OBJ_LIST=$(oci os object list --bucket-name "$BUCKET" --auth instance_principal --query "data[*].{name:name,size:size}" --output json --all 2>/dev/null || true)
  if [ -n "$OBJ_LIST" ] && [ "$OBJ_LIST" != "[]" ] && [ "$OBJ_LIST" != "null" ]; then
    total_bytes=$(echo "$OBJ_LIST" | python3 -c "import sys,json; data=json.load(sys.stdin); print(sum(o['size'] for o in data))" 2>/dev/null || true)
    obj_count=$(echo "$OBJ_LIST" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || true)
    if [ -n "$total_bytes" ] && [ -n "$obj_count" ]; then
      total_mb=$(python3 -c "print(f'{int($total_bytes)/1048576:.0f}')" 2>/dev/null || true)
      total_gb=$(python3 -c "print(f'{int($total_bytes)/1073741824:.1f}')" 2>/dev/null || true)
      pct_pretty=$(python3 -c "print(f'{int($total_bytes)/10737418240*100:.1f}')" 2>/dev/null || true)
      last_name=$(echo "$OBJ_LIST" | python3 -c "import sys,json; names=[o['name'] for o in json.load(sys.stdin)]; print(sorted(names)[-1])" 2>/dev/null || true)
      last_date=$(echo "$last_name" | sed -n 's/^s1-backup-\([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\)\.tar\.gz$/\1/p')
      if [ -n "$last_date" ]; then
        D=$(echo "$last_date" | cut -d- -f3 | sed 's/^0//')
        M=$(echo "$last_date" | cut -d- -f2 | sed 's/^0//')
        case "$M" in
          1) MESE_B="Gen" ;; 2) MESE_B="Feb" ;; 3) MESE_B="Mar" ;; 4) MESE_B="Apr" ;;
          5) MESE_B="Mag" ;; 6) MESE_B="Giu" ;; 7) MESE_B="Lug" ;; 8) MESE_B="Ago" ;;
          9) MESE_B="Set" ;; 10) MESE_B="Ott" ;; 11) MESE_B="Nov" ;; 12) MESE_B="Dic" ;;
        esac
        last_date="${D} ${MESE_B}"
      else
        last_date="?"
      fi
      backup_line="${total_mb} MB / 10 GB (${pct_pretty}%) · ${obj_count} oggetti · retention 7 gg · ultimo: ${last_date} ✅"
    fi
  else
    backup_line="bucket vuoto o non accessibile"
  fi
else
  backup_line="OCI CLI non disponibile"
fi

# ── 3. Database ───────────────────────────────────────────────────────────
check_db() {
  local container="$1" label="$2" engine="$3"
  if container_up "$container"; then
    printf '   %-12s %-12s %s' "${label}" "(${engine})" "✅"
  else
    printf '   %-12s %-12s %s' "${label}" "(${engine})" "❌"
  fi
}

db_report="$(check_db "forgejo-db" "Forgejo" "PostgreSQL")"$'\n'
db_report+="$(check_db "analytics-postgres" "Analytics" "PostgreSQL")"$'\n'
db_report+="$(check_db "cinebase-mariadb" "CineBase" "MariaDB")"

# ── 4. Componi e invia ────────────────────────────────────────────────────
echo ">> Invio report Telegram..."

TEXT=$(cat <<ETX
📊 <b>Report giornaliero s1</b> — ${DATA_ITA}

${status_emoji} <b>Servizi</b> — ${status_line}
${srvs}

💾 <b>Backup OCI</b> — ${BUCKET}
   ${backup_line}

🏥 <b>Database</b>
${db_report}
ETX
)

send_tg "$TEXT"
echo "   Report inviato."

REPORTEOF

chmod +x "$DOCKER_DIR/status-report.sh"
echo "   $DOCKER_DIR/status-report.sh creato."

# ── 3. Cron job per report ogni giorno alle 15:00 UTC (17:00 CEST) ───────
echo ">> Configurazione cron job (report giornaliero alle 15:00 UTC = 17:00 CEST)..."
CRON_LINE="0 15 * * * $DOCKER_DIR/status-report.sh"
(crontab -l 2>/dev/null | grep -v '^CRON_TZ=' | grep -v 'status-report.sh' || true; echo "$CRON_LINE") | crontab -
echo "   Cron job configurato."

echo ""
echo "=== Report giornaliero configurato ==="
echo ""
echo "Script creato sul server:"
echo "  $DOCKER_DIR/status-report.sh   — report giornaliero via Telegram"
echo ""
echo "Test manuale:"
echo "  $DOCKER_DIR/status-report.sh"
echo ""
echo "Verifica cron:"
echo "  crontab -l | grep status"
