#!/bin/bash
# =============================================================================
# 10-setup-backup.sh — Configurazione backup automatico su OCI Object Storage
# Server: malafronte-oci-s1 (ARM Ubuntu 24.04)
#
# Cosa fa:
#   - Verifica prerequisiti (OCI CLI + Instance Principal)
#   - Crea le directory di staging/backup locali (~/backup/)
#   - Genera lo script di backup giornaliero (~/docker/backup.sh)
#   - Crea lo script di deploy rapido (~/docker/deploy.sh)
#   - Configura il cron job per backup notturno alle 3:00
#
# Cosa backuppa (vedi ~/docker/backup.sh):
#   - PostgreSQL Forgejo (dump consistente via pg_dumpall)
#   - PostgreSQL Analytics Waline+Umami (dump consistente via pg_dumpall)
#   - MariaDB CineBase (dump consistente via mariadb-dump)
#   - ~/docker/forgejo/data/ (allegati, avatar, LFS)
#   - ~/docker/registry/auth/ (htpasswd)
#   - ~/docker/traefik/certificates/ (acme.json — evita rate limit Let's Encrypt)
#   - volume cinebase_*media-uploads (cover immagini)
#
# Cosa NON backuppa (ricostruibili):
#   - ~/docker/registry/data/ (immagini Docker — rebuildate dal CI/CD)
#   - ~/docker/postgres/data/ (sostituito dal dump SQL consistente)
#   - ~/docker/forgejo/runner*/data/ (config runner CI/CD)
#   - configurazioni Traefik (versionate nel repo)
#
# Prerequisito:
#   1. OCI CLI già installata sul server (script ufficiale Oracle, vedi docs/guida-backup-oci.md)
#   2. Bucket OCI già creato (vedi ../../docs/guida-backup-oci.md e oci-setup/README.md)
#   3. Dynamic Group e Policy IAM già configurati per Instance Principal
#
# Da eseguire come:  bash 10-setup-backup.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/.env" ]; then
  source <(sed 's/\r$//' "$SCRIPT_DIR/.env")
else
  echo "ERRORE: File .env non trovato in $SCRIPT_DIR"
  echo "Copia .env.example in .env e inserisci i valori reali."
  exit 1
fi

echo "=== [10] Setup Backup automatico su OCI ==="

DOCKER_DIR="$HOME/docker"
BACKUP_DIR="$HOME/backup"

# ── 1. Directory locali ────────────────────────────────────────────────────
mkdir -p "$BACKUP_DIR/staging"
echo ">> Directory di backup: $BACKUP_DIR"

# ── 2. Verifica OCI CLI ────────────────────────────────────────────────────
echo ">> Verifica OCI CLI..."
if ! command -v oci &> /dev/null; then
  echo "ATTENZIONE: OCI CLI non trovata. Installala con lo script ufficiale Oracle:"
  echo "  bash -c \"\$(curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh)\" -- --accept-all-defaults"
  echo "  hash -r  # ricarica PATH"
  echo ""
  echo "Poi verifica l'Instance Principal:"
  echo "  oci os object list --bucket-name ${BACKUP_BUCKET_NAME} --auth instance_principal"
  echo ""
  echo "Proseguo comunque con la creazione degli script (il backup girerà solo in locale)..."
else
  echo "   OCI CLI trovata: $(oci --version)"

  # Verifica accesso al bucket via Instance Principal
  echo ">> Verifica accesso al bucket '${BACKUP_BUCKET_NAME}' via Instance Principal..."
  if oci os object list --bucket-name "${BACKUP_BUCKET_NAME}" --auth instance_principal &>/dev/null; then
    echo "   Accesso al bucket OK."
  else
    echo "   ATTENZIONE: accesso al bucket fallito."
    echo "   Configura Dynamic Group + Policy IAM (vedi docs/guida-backup-oci.md e oci-setup/README.md)"
    echo "   Lo script verrà comunque installato; l'upload fallirà finché IAM non sarà a posto."
  fi
fi

# ── 3. Script di backup (embedded) ─────────────────────────────────────────
echo ">> Creazione script ~/docker/backup.sh..."
cat > "$DOCKER_DIR/backup.sh" << 'BACKUPEOF'
#!/bin/bash
# =============================================================================
# backup.sh — Backup giornaliero di s1 su OCI Object Storage
# Generated by 10-setup-backup.sh (non editare a mano: viene rigenerato)
#
# Strategia:
#   1. Dump SQL consistente di tutti i DB (Forgejo, Analytics, CineBase)
#   2. Tar dei volumi bind-mount (forgejo/data, registry/auth, traefik/certificates)
#   3. Tar del volume Docker cinebase_*media-uploads (cover immagini)
#   4. Un unico archivio s1-backup-YYYY-MM-DD.tar.gz caricato su OCI
#
# NON include (ricostruibili): registry/data, postgres/data raw, runner*/data
# =============================================================================
set -o pipefail

# Assicura che oci CLI sia trovabile dal cron (PATH minimale di default)
export PATH="$HOME/bin:$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:$PATH"

DATE=$(date +%Y-%m-%d)
DATE_SHORT=$(date +%Y%m%d)
TS() { date '+%Y-%m-%d %H:%M:%S'; }

BACKUP_DIR="$HOME/backup"
STAGING="$BACKUP_DIR/staging"
ARCHIVE="$BACKUP_DIR/s1-backup-${DATE}.tar.gz"
LOG_FILE="$BACKUP_DIR/backup.log"
RETENTION_DAYS_LOCAL=3
RETENTION_DAYS_REMOTE=30
BUCKET="${BACKUP_BUCKET_NAME:-s1-backup}"

mkdir -p "$STAGING/files"
rm -rf "${STAGING:?}/"/* 2>/dev/null || true

log() { echo "[$(TS)] $*" | tee -a "$LOG_FILE"; }

# Estrai una singola variabile da un file .env (robusto a valori con caratteri
# speciali come ), ==, ! — il `source` diretto fallirebbe su questi caratteri).
load_var() {
  local file="$1" key="$2"
  [ -f "$file" ] || return 0
  grep -E "^${key}=" "$file" 2>/dev/null | head -n1 | sed "s/^${key}=//" | tr -d '\r'
}

log "=== Inizio backup s1 ==="

# Carica solo le variabili strettamente necessarie (NON source completo)
export BACKUP_BUCKET_NAME="${BACKUP_BUCKET_NAME:-$(load_var "$HOME/scripts/.env" BACKUP_BUCKET_NAME)}"
export MYSQL_ROOT_PASSWORD="$(load_var "$HOME/docker/cinebase/.env" MYSQL_ROOT_PASSWORD)"

container_running() { docker ps --format '{{.Names}}' 2>/dev/null | grep -qx "$1"; }

# ── 1. Dump PostgreSQL Forgejo (forgejo-db) ────────────────────────────────
if container_running forgejo-db; then
  log "Dump PostgreSQL Forgejo..."
  if docker exec forgejo-db pg_dumpall -U forgejo 2>>"$LOG_FILE" \
        > "$STAGING/forgejo-postgres-${DATE_SHORT}.sql"; then
    log "   OK forgejo-db: $(du -h "$STAGING/forgejo-postgres-${DATE_SHORT}.sql" | cut -f1)"
  else
    log "   ERRORE dump forgejo-db (postgres può ancora essere consistente, verificare)"
  fi
else
  log "SKIP forgejo-db: container non in esecuzione"
fi

# ── 2. Dump PostgreSQL Analytics (Waline + Umami) ──────────────────────────
if container_running analytics-postgres; then
  log "Dump PostgreSQL Analytics..."
  if docker exec analytics-postgres pg_dumpall -U analytics 2>>"$LOG_FILE" \
        > "$STAGING/analytics-postgres-${DATE_SHORT}.sql"; then
    log "   OK analytics-postgres: $(du -h "$STAGING/analytics-postgres-${DATE_SHORT}.sql" | cut -f1)"
  else
    log "   ERRORE dump analytics-postgres"
  fi
else
  log "SKIP analytics-postgres: container non in esecuzione"
fi

# ── 3. Dump MariaDB CineBase ───────────────────────────────────────────────
if container_running cinebase-mariadb; then
  if [ -n "${MYSQL_ROOT_PASSWORD:-}" ]; then
    log "Dump MariaDB CineBase..."
    if docker exec cinebase-mariadb mariadb-dump \
          -uroot -p"$MYSQL_ROOT_PASSWORD" \
          --all-databases --single-transaction \
          --routines --triggers --events \
          2>>"$LOG_FILE" > "$STAGING/cinebase-mariadb-${DATE_SHORT}.sql"; then
      log "   OK cinebase-mariadb: $(du -h "$STAGING/cinebase-mariadb-${DATE_SHORT}.sql" | cut -f1)"
    else
      log "   ERRORE dump cinebase-mariadb"
    fi
  else
    log "SKIP cinebase-mariadb: MYSQL_ROOT_PASSWORD non disponibile in ~/docker/cinebase/.env"
  fi
else
  log "SKIP cinebase-mariadb: container non in esecuzione"
fi

# ── 4. Tar del volume media-uploads di CineBase (cover immagini) ───────────
MEDIA_VOL=$(docker volume ls --filter name=media-uploads -q 2>/dev/null | head -n1 || true)
if [ -n "$MEDIA_VOL" ]; then
  log "Dump volume '$MEDIA_VOL' (media-uploads)..."
  if docker run --rm \
        -v "${MEDIA_VOL}:/data:ro" \
        -v "${STAGING}:/backup" \
        alpine \
        tar czf "/backup/cinebase-media-uploads-${DATE_SHORT}.tar.gz" -C /data . \
        2>>"$LOG_FILE"; then
    log "   OK media-uploads: $(du -h "$STAGING/cinebase-media-uploads-${DATE_SHORT}.tar.gz" | cut -f1)"
  else
    log "   ERRORE dump media-uploads (volume: $MEDIA_VOL)"
  fi
else
  log "SKIP media-uploads: nessun volume *media-uploads* trovato"
fi

# ── 5. Tar file statici bind-mount via container helper ────────────────────
# Necessario perché alcuni file sono root-only (acme.json 0600) o di altri
# utenti (forgejo/data di proprietà di 'opc'); un container Docker gira come
# root e può leggerli. Stesso pattern usato per media-uploads.
tar_dir_via_docker() {
  local src="$1" name="$2"
  if [ -d "$src" ]; then
    if docker run --rm \
          -v "${src}:/data:ro" \
          -v "${STAGING}:/backup" \
          alpine \
          tar czf "/backup/${name}.tar.gz" -C /data . \
          2>>"$LOG_FILE"; then
      log "   OK $name: $(du -h "$STAGING/${name}.tar.gz" | cut -f1)"
    else
      log "   ERRORE tar $name (src=$src)"
    fi
  else
    log "   SKIP $name: $src non trovato"
  fi
}

log "Tar file statici (forgejo/data, registry/auth, traefik/certificates)..."
tar_dir_via_docker "$HOME/docker/forgejo/data"       "forgejo-data"
tar_dir_via_docker "$HOME/docker/registry/auth"      "registry-auth"
tar_dir_via_docker "$HOME/docker/traefik/certificates" "traefik-certificates"

# ── 6. Composizione archivio finale unico ──────────────────────────────────
log "Composizione archivio finale: $ARCHIVE"
tar czf "$ARCHIVE" -C "$STAGING" . 2>>"$LOG_FILE"
ARCHIVE_SIZE=$(du -h "$ARCHIVE" | cut -f1)
log "   Archivio creato: $ARCHIVE_SIZE"

# ── 7. Pulizia staging ─────────────────────────────────────────────────────
rm -rf "${STAGING:?}/"/* 2>/dev/null || true

# ── 8. Upload su OCI Object Storage (Instance Principal) ───────────────────
if command -v oci &> /dev/null; then
  log "Upload su OCI bucket '$BUCKET'..."
  if oci os object put \
        --bucket-name "$BUCKET" \
        --file "$ARCHIVE" \
        --name "s1-backup-${DATE}.tar.gz" \
        --auth instance_principal \
        --force \
        2>&1 | tee -a "$LOG_FILE"; then
    log "Upload completato ($ARCHIVE_SIZE)"
  else
    log "ERRORE upload OCI (backup resta disponibile localmente: $ARCHIVE)"
  fi
else
  log "OCI CLI non disponibile: backup salvato solo localmente: $ARCHIVE"
fi

# ── 9. Retention locale (keep ultimi N giorni) ─────────────────────────────
find "$BACKUP_DIR" -maxdepth 1 -type f -name "s1-backup-*.tar.gz" -mtime +"$RETENTION_DAYS_LOCAL" -delete 2>/dev/null || true

# ── 10. Retention remota OCI (cancella oggetti con data < cutoff) ──────────
# Implementata lato script perché più affidabile della lifecycle rule OCI
# (che richiede una policy service aggiuntiva e prompt interattivi via CLI).
# La data è parsata dal nome oggetto: s1-backup-YYYY-MM-DD.tar.gz
if command -v oci &> /dev/null; then
  CUTOFF=$(date -d "${RETENTION_DAYS_REMOTE} days ago" +%Y-%m-%d 2>/dev/null || date -v-"${RETENTION_DAYS_REMOTE}"d +%Y-%m-%d 2>/dev/null || true)
  if [ -n "$CUTOFF" ]; then
    log "Retention remota: elimina oggetti con data < $CUTOFF..."
    DELETED=0
    while read -r obj; do
      obj_date=$(echo "$obj" | sed -n 's/^s1-backup-\([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\)\.tar\.gz$/\1/p')
      if [ -n "$obj_date" ] && [ "$obj_date" \< "$CUTOFF" ]; then
        oci os object delete --bucket-name "$BUCKET" --name "$obj" \
          --auth instance_principal --force 2>>"$LOG_FILE" \
          && log "   Deleted $obj (data $obj_date)" \
          || log "   WARN: delete fallito per $obj"
        DELETED=$((DELETED + 1))
      fi
    done < <(oci os object list --bucket-name "$BUCKET" --auth instance_principal --all \
              --query "data[*].name" 2>/dev/null \
              | grep -oE 's1-backup-[0-9]{4}-[0-9]{2}-[0-9]{2}\.tar\.gz' \
              | sort -u)
    if [ "$DELETED" -gt 0 ]; then
      log "   Retention remota: $DELETED oggetti eliminati."
    else
      log "   Retention remota: nessun oggetto da eliminare."
    fi
  fi
fi

log "=== Backup completato: $ARCHIVE_SIZE ==="
BACKUPEOF

chmod +x "$DOCKER_DIR/backup.sh"
echo "   ~/docker/backup.sh creato."

# ── 4. Script di deploy (utility, invariato) ───────────────────────────────
echo ">> Creazione script ~/docker/deploy.sh..."
cat > "$DOCKER_DIR/deploy.sh" << 'DEPLOYEOF'
#!/bin/bash
# =============================================================================
# deploy.sh — Deploy rapido di un progetto docker-compose
# Uso: ./deploy.sh <nome-progetto>
# =============================================================================
set -euo pipefail

PROJECT="${1:-}"
if [ -z "$PROJECT" ]; then
  echo "Uso: ./deploy.sh <nome-progetto>"
  echo "Esempio: ./deploy.sh cinebase"
  exit 1
fi

if [ ! -d "$HOME/docker/$PROJECT" ]; then
  echo "ERRORE: Cartella ~/docker/$PROJECT non trovata."
  exit 1
fi

cd "$HOME/docker/$PROJECT" || exit 1

echo ">> Deploy di '$PROJECT'..."
docker compose pull
docker compose up -d
docker image prune -f

echo ">> Deploy completato: $PROJECT"
DEPLOYEOF

chmod +x "$DOCKER_DIR/deploy.sh"
echo "   ~/docker/deploy.sh creato."

# ── 5. Cron job per backup notturno (3:00 Europe/Rome) ─────────────────────
echo ">> Configurazione cron job (backup ogni giorno alle 3:00)..."
CRON_LINE="0 3 * * * $DOCKER_DIR/backup.sh >> $BACKUP_DIR/backup.cron.log 2>&1"
( crontab -l 2>/dev/null | grep -v 'backup.sh' || true; echo "$CRON_LINE" ) | crontab -
echo "   Cron job configurato."

echo ""
echo "=== Backup configurato ==="
echo ""
echo "Script creati sul server:"
echo "  $DOCKER_DIR/backup.sh   — backup manuale o via cron"
echo "  $DOCKER_DIR/deploy.sh   — deploy rapido di un progetto"
echo ""
echo "Directory locali:"
echo "  $BACKUP_DIR/                    — archivi .tar.gz (retention 3 giorni)"
echo "  $BACKUP_DIR/backup.log          — log dettagliato"
echo ""
echo "Test manuale (consigliato al primo deploy):"
echo "  $DOCKER_DIR/backup.sh"
echo ""
echo "Verifica cron:"
echo "  crontab -l | grep backup"
echo ""
echo "Verifica backup su OCI (dal PC, vedi docs/guida-backup-oci.md):"
echo "  oci os object list --bucket-name ${BACKUP_BUCKET_NAME}"
echo ""
echo "Ripristino (vedi docs/guida-backup-oci.md §6):"
echo "  oci os object get --bucket-name ${BACKUP_BUCKET_NAME} \\"
echo "    --name s1-backup-YYYY-MM-DD.tar.gz --file /tmp/restore.tar.gz"
